### ISSUE TITLE
What model is maple-diffusion using

### ISSUE THREAD

**Issue by Jerry23011** [madebyollin/maple-diffusion#26]
Hi, just want to know which model does maple-diffusion use for training?

**Comment by Jerry23011** [comment]
I know it's Stable Diffusion, just want to know what is the data you are using for training.

**Comment by madebyollin** [comment]
`maple-diffusion` does not include any model weights, training code, or training data; you (the user) can bring whichever trained model weights you want to use.

The screenshots / instructions in the README use stability.ai's original Stable Diffusion 1.4 model, which was reportedly trained on various subsets of LAION-5B in some complicated sequence (per their [model card](https://huggingface.co/CompVis/stable-diffusion-v1-4)) :)

**Comment by Jerry23011** [comment]
thanks
