### ISSUE TITLE
How to obtain the `.ckpt` file from original stable diffusion model?

### ISSUE THREAD

**Issue by geekinglcq** [madebyollin/maple-diffusion#30]
Hi, thank you for your amazing job. I am trying to convert the stable diffusion model but I met some problems.   
I have found that the original stable diffusion model consists of many files, configs and model bins, but here the convert script seems only receive single file as input. 
So, How to obtain the single `.ckpt` file from the original stable diffusion model? It's ok to save one of the module's state_dict such as `unet`, but how about other modules?

**Comment by madebyollin** [comment]
I've corrected the v1.4 link in the README to point to https://huggingface.co/CompVis/stable-diffusion-v-1-4-original, which should have the single `.ckpt` file available.

**Comment by geekinglcq** [comment]
Thanks~ Problem solved.
