### ISSUE TITLE
HELLO GOOD DAY TO ALL, SOMEONE KNOWS IF IT POSIBLE TO RUN IT ALSO IN IPHONE 11, and 12?

### ISSUE THREAD

**Issue by SANTINO27** [madebyollin/maple-diffusion#32]

**Comment by madebyollin** [comment]
I DON'T THINK SO, 4GB OF RAM WAS [TOO SMALL](https://github.com/madebyollin/maple-diffusion/issues/25).

TRY LIULIU'S IMPLEMENTATION (https://github.com/liuliu/swift-diffusion, https://drawthings.ai) OR APPLE's (https://github.com/apple/ml-stable-diffusion) :)

**Comment by SANTINO27** [comment]
HELLO , THANK YOU VERY MUCH FOR THE HELP 🤍🤍🤍🤍
